import mock from '../mock';
import user1 from 'src/assets/images/profile/user-1.jpg';
import user2 from 'src/assets/images/profile/user-2.jpg';
import user3 from 'src/assets/images/profile/user-3.jpg';
import user4 from 'src/assets/images/profile/user-4.jpg';
import user5 from 'src/assets/images/profile/user-5.jpg';

const COMRiskData = [
  {
    Id: 6611001,
    Category: 'Clinic',
    subCategory: 'subcategory',
    riskDate: '02-12-2021',
    Location: 'IPD',
    Area: 'ชั้น 3',
    HN: '90090',
    An: '12345678910',
    Witness: 'Karnanan Purimanuruk',
    Div: 'แผนกเทคโนโลยีสารสนเทศ',
    Detail:
      'ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos',
    FirstManage: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta',
    Suggestion: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta',
    Date: '02-12-2021',
    thumb: user1,
    user: 'Karnanan Purimanuruk',
    Status: 'รอพิจารณา',
  },
  {
    Id: 6611002,
    Category: 'Clinic',
    subCategory: 'subcategory',
    riskDate: '02-12-2021',
    Location: 'IPD',
    Area: 'ชั้น 3',
    HN: '90090',
    An: '12345678910',
    Witness: 'Karnanan Purimanuruk',
    Div: 'แผนกเทคโนโลยีสารสนเทศ',
    Detail:
      'ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos',
    FirstManage: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta',
    Suggestion: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta',
    Date: '02-12-2021',
    thumb: user1,
    user: 'Karnanan Purimanuruk',
    Status: 'รอพิจารณา',
  },
  {
    Id: 6611003,
    Category: 'Clinic',
    subCategory: 'subcategory',
    riskDate: '02-12-2021',
    Location: 'IPD',
    Area: 'ชั้น 3',
    HN: '90090',
    An: '12345678910',
    Witness: 'Karnanan Purimanuruk',
    Div: 'แผนกเทคโนโลยีสารสนเทศ',
    Detail:
      'ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos',
    FirstManage: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta',
    Suggestion: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta',
    Date: '02-12-2021',
    thumb: user1,
    user: 'Karnanan Purimanuruk',
    Status: 'รอพิจารณา',
  },
  {
    Id: 6611004,
    Category: 'Clinic',
    subCategory: 'subcategory',
    riskDate: '02-12-2021',
    Location: 'IPD',
    Area: 'ชั้น 3',
    HN: '90090',
    An: '12345678910',
    Witness: 'Karnanan Purimanuruk',
    Div: 'แผนกเทคโนโลยีสารสนเทศ',
    Detail:
      'ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos',
    FirstManage: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta',
    Suggestion: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta',
    Date: '02-12-2021',
    thumb: user1,
    user: 'Karnanan Purimanuruk',
    Status: 'รอพิจารณา',
  },
  {
    Id: 6611005,
    Category: 'Clinic',
    subCategory: 'subcategory',
    riskDate: '02-12-2021',
    Location: 'IPD',
    Area: 'ชั้น 3',
    HN: '90090',
    An: '12345678910',
    Witness: 'Karnanan Purimanuruk',
    Div: 'แผนกเทคโนโลยีสารสนเทศ',
    Detail:
      'ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos',
    FirstManage: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta',
    Suggestion: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta',
    Date: '02-12-2021',
    thumb: user1,
    user: 'Karnanan Purimanuruk',
    Status: 'รอพิจารณา',
  },
  {
    Id: 6611006,
    Category: 'Clinic',
    subCategory: 'subcategory',
    riskDate: '02-12-2021',
    Location: 'IPD',
    Area: 'ชั้น 3',
    HN: '90090',
    An: '12345678910',
    Witness: 'Karnanan Purimanuruk',
    Div: 'แผนกเทคโนโลยีสารสนเทศ',
    Detail:
      'ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos',
    FirstManage: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta',
    Suggestion: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta',
    Date: '02-12-2021',
    thumb: user1,
    user: 'Karnanan Purimanuruk',
    Status: 'รอพิจารณา',
  },
  {
    Id: 6611007,
    Category: 'Clinic',
    subCategory: 'subcategory',
    riskDate: '02-12-2021',
    Location: 'IPD',
    Area: 'ชั้น 3',
    HN: '90090',
    An: '12345678910',
    Witness: 'Karnanan Purimanuruk',
    Div: 'แผนกเทคโนโลยีสารสนเทศ',
    Detail:
      'ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos',
    FirstManage: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta',
    Suggestion: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta',
    Date: '02-12-2021',
    thumb: user1,
    user: 'Karnanan Purimanuruk',
    Status: 'รอพิจารณา',
  },
  {
    Id: 6611008,
    Category: 'Clinic',
    subCategory: 'subcategory',
    riskDate: '02-12-2021',
    Location: 'IPD',
    Area: 'ชั้น 3',
    HN: '90090',
    An: '12345678910',
    Witness: 'Karnanan Purimanuruk',
    Div: 'แผนกเทคโนโลยีสารสนเทศ',
    Detail:
      'ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos',
    FirstManage: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta',
    Suggestion: 'ab illo inventore veritatis et quasi architecto beatae vitae dicta',
    Date: '02-12-2021',
    thumb: user1,
    user: 'Karnanan Purimanuruk',
    Status: 'รอพิจารณา',
  },
];

mock.onGet('/api/data/risk/COMRiskData').reply(() => {
  return [200, COMRiskData];
});
export default COMRiskData;
